name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up npm
      run: npm ci

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: build Webpack and copy
      run: cd shop-front && npm run build && mkdir ../shop-back/public && mv build ../shop-back/public/      

    - name: Build
      run: cd shop-back && go build -v ./...

    - name: Test
      run: cd shop-back && go test -v ./...
    
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v11
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: d3fau1t-shop
        environment_name: D3fau1tshop-env
        region: ap-northeast-2
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip

    - name: Success
      run: echo deployed successfully.
